call ../../yii migrate/down --migrationPath=@console/migrations/data --interactive=0
call ../../yii migrate/down --migrationPath=@themes/project/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/plugin-social-meta/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/plugin-file-manager/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-notify/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-notify/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-notify/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-forms/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-forms/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-forms/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-core/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-core/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-core/migrations --interactive=0
call ../../yii migrate/down --migrationPath=@cmsgears/module-core/migrations --interactive=0
